=head1 Some hot chapter title

=head2 Autor

Steffen Schwigon E<lt>steffen.schwigon@amd.comE<gt>

=head2 Abstract

A hopefully useful abstract.

=head2 Foo

Foo

=head2 Bar

Bar

=head2 Some verbatim

    my $affe = Birne->new( %params );
    $affe->zomtec ($kram );

=over 4

=item * affe

=item * tiger

=item * zomtec

=back

=head2 Baz

Baz

