@node Command line interface, Web User Interface, Preconditions, Top
@chapter Command line interface

@menu
* Commandline Synopsis::        
* Scheduling::                  
@end menu

@node Commandline Synopsis, Scheduling, Command line interface, Command line interface
@section Commandline Synopsis

@itemize

@item Get host usage/scheduling overview

@item Create hosts

@item Create queues

@item Create hosts/queue bindings

@end itemize

@node Scheduling,  , Commandline Synopsis, Command line interface
@section Scheduling

@menu
* Create new queue and new host and bind both together::  
* Change queue priority::       
* requested features::          
* Cancel current testrun on host::  
@end menu

@node Create new queue and new host and bind both together, Change queue priority, Scheduling, Scheduling
@subsection Create new queue and new host and bind both together

@itemize

@item Show existing queues with priorities

@example
@verbatim
$ tapper-testrun listqueue -v
        10 |              AdHoc |  1000
        11 |      kernel_reboot |   100
         4 | xen-3.3-testing-32 |   100
         5 | xen-3.3-testing-64 |   100
         7 | xen-3.4-testing-32 |   100
         6 | xen-3.4-testing-64 |   100
         9 |    xen-unstable-32 |   100
         8 |    xen-unstable-64 |   100
@end verbatim
@end example

@item Create new queue @emph{oprofile}

@example
@verbatim
$ tapper-testrun newqueue --name=oprofile \
                          --priority=200
12
@end verbatim
@end example

@item Create new host @emph{bullock} and bind it to queue @emph{oprofile}

@example
@verbatim
$ tapper-testrun newhost --name=bullock \
                         --queue=oprofile
10
@end verbatim
@end example

@item Show existing hosts

Note that the new host @emph{bullock} is initially deactivated.

@example
@verbatim
$ tapper-testrun listhost -v
         8 |  amarok | deactivated |   free
         1 |  athene |      active | in use
         9 |   azael | deactivated |   free
        10 | bullock | deactivated |   free | oprofile
         4 |    cook | deactivated |   free
         6 | incubus | deactivated |   free
         2 |  kobold |      active | in use
         5 |  lemure |      active | in use
         3 |   satyr |      active | in use
         7 |    uruk | deactivated |   free
@end verbatim
@end example

@item Activate host @emph{bullock}

Note that this command is ID based (bullock has id 10) because you
can rename hosts.

@example
@verbatim
$ tapper-testrun updatehost --id=10 --active
10 | bullock | active | free | oprofile
@end verbatim
@end example

@item Again, show existing hosts

Host @emph{bullock} is now activated.

@example
@verbatim
$ tapper-testrun listhost -v
         8 |  amarok | deactivated |   free
         1 |  athene |      active | in use
         9 |   azael | deactivated |   free
        10 | bullock |      active |   free | oprofile
         4 |    cook | deactivated |   free
         6 | incubus | deactivated |   free
         2 |  kobold |      active | in use
         5 |  lemure |      active | in use
         3 |   satyr |      active | in use
         7 |    uruk | deactivated |   free
@end verbatim
@end example

@end itemize

Done.

@node Change queue priority, requested features, Create new queue and new host and bind both together, Scheduling
@subsection Change queue priority

@itemize

@item List existing queues

@example
@verbatim
$ tapper-testrun listqueue -v
        10 |              AdHoc |  1000
        11 |      kernel_reboot |   100
        12 |           oprofile |   200 | bullock
         4 | xen-3.3-testing-32 |   100
         5 | xen-3.3-testing-64 |   100
         7 | xen-3.4-testing-32 |   100
         6 | xen-3.4-testing-64 |   100
         9 |    xen-unstable-32 |   100
         8 |    xen-unstable-64 |   100
@end verbatim
@end example

@item Update queue

@example
@verbatim
$ tapper-testrun updatequeue --name=oprofile \
                             --priority=1000
12
@end verbatim
@end example

@item Again, list existing queues

@example
@verbatim
$ tapper-testrun listqueue -v
        10 |              AdHoc |  1000
        11 |      kernel_reboot |   100
        12 |           oprofile |  1000 | bullock
         4 | xen-3.3-testing-32 |   100
         5 | xen-3.3-testing-64 |   100
         7 | xen-3.4-testing-32 |   100
         6 | xen-3.4-testing-64 |   100
         9 |    xen-unstable-32 |   100
         8 |    xen-unstable-64 |   100
@end verbatim
@end example

Done.

@end itemize

@node requested features, Cancel current testrun on host, Change queue priority, Scheduling
@subsection requested features

Hosts for testruns can be choosen based on requested
features. Supported features are:

@itemize

@item hostname

@item mem

@item vendor

@item family

@item model

@item stepping

@item revision

@item socket

@item cores

@item clock

@item l2cache

@item l3cache

@end itemize

@node Cancel current testrun on host,  , requested features, Scheduling
@subsection Cancel current testrun on host

Freeing a host need the config for the currently running
testrun. Thus, the command is only tested on bancroft and may not work
on other machines.

@example
@verbatim
$ tapper-testrun freehost \
                 --name=bullock\
                 --desc='I need this host right now'
@end verbatim
@end example

