\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename tapper-manual.info
@settitle Tapper User Manual
@afourpaper
@setchapternewpage odd
@c %**end of header

@c see http://www.slac.stanford.edu/comp/unix/gnu-info/texinfo2_3.html#SEC17
@c Emacs commands:
@c M-x texinfo-multiple-files-update
@c M-x texinfo-every-node-update

@ifinfo
This file documents the Tapper Test and Automation Infrastructure

Copyright 2008-2011 AMD Operating System Research Center

@end ifinfo

@c  This title page illustrates only one of the
@c  two methods of forming a title page.

@titlepage

@title Tapper
@subtitle Test and Automation Infrastructure
@subtitle User Manual
@author Steffen Schwigon, Maik Hentsche

@c  The following two commands
@c  start the copyright page.
@page
@vskip 0pt plus 1filll
Copyright @copyright{} 2008-2011 AMD Operating System Research Center
@end titlepage

@node Top, Synopsis, (dir), (dir)

@ifinfo
This document describes the Tapper Test and Automation Infrastructure

This document applies to version 3 of Tapper.

@end ifinfo

@menu
* Synopsis::                    
* Technical Infrastructure::    
* Test Protocol::               
* Test Suite Wrappers::         
* Preconditions::               
* Command line interface::      
* Web User Interface::          
* Reports API::                 
* Complete Use Cases::          
@end menu

@paragraphindent 0

@contents

@macro TODO{content}
@cartouche
@strong{TODO} \content\
@end cartouche
@end macro

@macro preconditions{} 
@emph{preconditions} 
@end macro

@macro tapper
@emph{Tapper}
@end macro

@include chapter-synopsis.texi
@include chapter-infrastructure.texi
@include chapter-tap.texi
@include chapter-testsuites.texi
@include chapter-preconditions.texi
@include chapter-commandline.texi
@include chapter-webgui.texi
@include chapter-reports-api.texi
@include chapter-usecases.texi

@bye
